- name: "powershell_dsc"
  hosts: all

  vars:
    windowsfeature_name: "telnet-client"

  tasks:
  ## https://docs.microsoft.com/en-us/powershell/dsc/windowsfeatureresource
    - name: "Ensure state of Windows Feature"
      win_dsc:
        resource_name: windowsfeature
        name: "{{ windowsfeature_name }}"
        ensure: present
